// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unpkytftbetzoernnedc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucGt5dGZ0YmV0em9lcm5uZWRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDU4ODQsImV4cCI6MjA3MzkyMTg4NH0.6s-W5MGKnvMP8A-9ODTKg-r_vKH3J8u6keKt6KNm3tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});